# Static assets for the SPA. config.json is generated by apply.sh from the
# 02-lambdas outputs, so the browser learns the Cognito and API endpoints.
locals {
  files = {
    "index.html"    = "text/html; charset=utf-8"
    "callback.html" = "text/html; charset=utf-8"
    "auth.js"       = "text/javascript; charset=utf-8"
    "app.js"        = "text/javascript; charset=utf-8"
    "style.css"     = "text/css; charset=utf-8"
    "config.json"   = "application/json"
  }
}

resource "aws_s3_object" "assets" {
  for_each     = local.files
  bucket       = var.web_bucket_name
  key          = each.key
  source       = "${path.module}/${each.key}"
  etag         = filemd5("${path.module}/${each.key}")
  content_type = each.value
  # The demo is reapplied often; never let a browser cache a stale endpoint.
  cache_control = "no-store"
}
